### ISSUE TITLE
Error with multiple-sequence file

### ISSUE THREAD

**Issue by thh32** [Matt-Schmitz/InvestiGut#3]
Hey Matt,

This issue has occurred when inputting the attached protein sequences.

From where the error occurs, I guess one of the proteins may not occur in the Danish samples and this is throwing the error? But not sure.

Best,
Tom

```
Traceback (most recent call last):

  File "/DATA/thitch/Protein_Ecology/Conda_testing/V1/InvestiGut/investigut.py", line 956, in <module>

    main()

  File "/DATA/thitch/Protein_Ecology/Conda_testing/V1/InvestiGut/investigut.py", line 599, in main

    next_letters.append(allletters[i])

                        ~~~~~~~~~~^^^

IndexError: string index out of range


```

[Marko_proteins.zip](https://github.com/Matt-Schmitz/InvestiGut/files/14570223/Marko_proteins.zip)

**Comment by thh32** [comment]
Error solved.

Due to code which created letters based on the proteins country occurance.
